// Knoux MorphCore™ | Visual Patch Lab - TypeScript Definitions
// Interactive Body Editing Tools - 50 Real Tools Across 8 Categories

export type ToolCategory =
  | "body-scale"
  | "waist-belly"
  | "chest"
  | "hips-thighs"
  | "legs-feet"
  | "arms-shoulders"
  | "head-face"
  | "freeform";

export type EditMode =
  | "brush"
  | "pinch"
  | "warp"
  | "curve"
  | "drag"
  | "sculpt"
  | "smooth"
  | "mirror";

export type IntensityLevel = "light" | "medium" | "strong" | "extreme";

export interface Point2D {
  x: number;
  y: number;
}

export interface EditRegion {
  id: string;
  points: Point2D[];
  intensity: number;
  brushSize: number;
  feather: number;
}

export interface EditOperation {
  id: string;
  toolId: string;
  timestamp: number;
  regions: EditRegion[];
  beforeSnapshot: string; // Base64 image data
  afterSnapshot: string;
  parameters: Record<string, any>;
}

export interface VisualPatchTool {
  id: string;
  name: string;
  nameAr: string;
  category: ToolCategory;
  description: string;
  descriptionAr: string;
  icon: string;
  editMode: EditMode;
  enabled: boolean;

  // Tool parameters
  defaultIntensity: number;
  maxIntensity: number;
  defaultBrushSize: number;
  maxBrushSize: number;
  defaultFeather: number;
  supportsSymmetry: boolean;
  requiresRegionSelection: boolean;

  // Visual settings
  cursorIcon: string;
  previewColor: string;
  overlayOpacity: number;

  // Performance
  realTimePreview: boolean;
  processingComplexity: "low" | "medium" | "high";
}

export interface EditSession {
  id: string;
  originalImage: string; // Base64
  currentImage: string; // Base64
  width: number;
  height: number;
  operations: EditOperation[];
  createdAt: Date;
  lastModified: Date;
  title: string;
}

export interface ToolSettings {
  intensity: number;
  brushSize: number;
  feather: number;
  symmetryEnabled: boolean;
  realTimePreview: boolean;
  snapToGrid: boolean;
  showGuides: boolean;
  preserveAspectRatio: boolean;
  autoSave: boolean;
  undoLevels: number;
}

export interface CanvasState {
  scale: number;
  offsetX: number;
  offsetY: number;
  rotation: number;
  isDrawing: boolean;
  isDragging: boolean;
  currentTool: string | null;
  selectedRegions: string[];
  guides: {
    horizontal: number[];
    vertical: number[];
  };
}

export interface EditHistory {
  operations: EditOperation[];
  currentIndex: number;
  maxHistory: number;
  hasUnsavedChanges: boolean;
}

export interface ExportOptions {
  format: "png" | "jpg" | "webp";
  quality: number;
  resolution: "original" | "hd" | "4k";
  includeMetadata: boolean;
  watermark?: {
    text: string;
    position:
      | "top-left"
      | "top-right"
      | "bottom-left"
      | "bottom-right"
      | "center";
    opacity: number;
  };
}

export interface BeforeAfterComparison {
  id: string;
  original: string;
  edited: string;
  timestamp: Date;
  toolsUsed: string[];
  editTime: number; // seconds
}

// Body Scale Tools (8 tools)
export const BODY_SCALE_TOOLS: VisualPatchTool[] = [
  {
    id: "body-scale-full-enlarge",
    name: "Enlarge Full Body",
    nameAr: "تكبير الجسم كاملاً",
    category: "body-scale",
    description: "Scale up entire body proportionally",
    descriptionAr: "تكبير الجسم بالكامل بشكل متناسب",
    icon: "🔍",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 100,
    defaultBrushSize: 150,
    maxBrushSize: 300,
    defaultFeather: 40,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#4ade80",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "body-scale-full-shrink",
    name: "Shrink Full Body",
    nameAr: "تصغير الجسم كاملاً",
    category: "body-scale",
    description: "Scale down entire body proportionally",
    descriptionAr: "تصغير الجسم بالكامل بشكل متناسب",
    icon: "🔎",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 80,
    defaultBrushSize: 150,
    maxBrushSize: 300,
    defaultFeather: 40,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#f87171",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "body-scale-upper-enlarge",
    name: "Enlarge Upper Body",
    nameAr: "تكبير الجزء العلوي",
    category: "body-scale",
    description: "Scale up chest, shoulders and arms",
    descriptionAr: "تكبير الصدر والكتفين والذراعين",
    icon: "💪",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 90,
    defaultBrushSize: 120,
    maxBrushSize: 250,
    defaultFeather: 35,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#60a5fa",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "body-scale-lower-enlarge",
    name: "Enlarge Lower Body",
    nameAr: "تكبير الجزء السفلي",
    category: "body-scale",
    description: "Scale up hips, thighs and legs",
    descriptionAr: "تكبير الأرداف والفخذين والساقين",
    icon: "🦵",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 90,
    defaultBrushSize: 120,
    maxBrushSize: 250,
    defaultFeather: 35,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#a78bfa",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "body-scale-height-extend",
    name: "Extend Height",
    nameAr: "تطويل القامة",
    category: "body-scale",
    description: "Stretch body vertically to appear taller",
    descriptionAr: "مد الجسم عمودياً لإظهار طول أكبر",
    icon: "📏",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 60,
    defaultBrushSize: 200,
    maxBrushSize: 400,
    defaultFeather: 50,
    supportsSymmetry: false,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#fbbf24",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "body-scale-height-compress",
    name: "Compress Height",
    nameAr: "تقصير القامة",
    category: "body-scale",
    description: "Compress body vertically to appear shorter",
    descriptionAr: "ضغط الجسم عمودياً لإظهار قصر القامة",
    icon: "📐",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 200,
    maxBrushSize: 400,
    defaultFeather: 50,
    supportsSymmetry: false,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#fb7185",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "body-scale-width-expand",
    name: "Expand Width",
    nameAr: "توسيع الجسم عرضاً",
    category: "body-scale",
    description: "Stretch body horizontally to appear wider",
    descriptionAr: "مد الجسم أفقياً لإظهار عرض أكبر",
    icon: "↔️",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 70,
    defaultBrushSize: 180,
    maxBrushSize: 350,
    defaultFeather: 45,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ew-resize",
    previewColor: "#34d399",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "body-scale-width-narrow",
    name: "Narrow Width",
    nameAr: "تضييق الجسم",
    category: "body-scale",
    description: "Compress body horizontally to appear narrower",
    descriptionAr: "ضغط الجسم أفقياً لإظهار نحافة أكبر",
    icon: "➡️⬅️",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 180,
    maxBrushSize: 350,
    defaultFeather: 45,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ew-resize",
    previewColor: "#f472b6",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
];

// Waist & Belly Tools (6 tools)
export const WAIST_BELLY_TOOLS: VisualPatchTool[] = [
  {
    id: "waist-slim",
    name: "Slim Waist",
    nameAr: "تنحيف الخصر",
    category: "waist-belly",
    description: "Narrow waist area for hourglass figure",
    descriptionAr: "تضييق منطقة الخصر للحصول على شكل الساعة الرملية",
    icon: "⏳",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 80,
    defaultBrushSize: 100,
    maxBrushSize: 200,
    defaultFeather: 30,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#8b5cf6",
    overlayOpacity: 0.35,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "belly-flatten",
    name: "Flatten Belly",
    nameAr: "تسطيح البطن",
    category: "waist-belly",
    description: "Flatten and tighten abdominal area",
    descriptionAr: "تسطيح وشد منطقة البطن",
    icon: "🏋️",
    editMode: "sculpt",
    enabled: true,
    defaultIntensity: 35,
    maxIntensity: 90,
    defaultBrushSize: 120,
    maxBrushSize: 220,
    defaultFeather: 40,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#06d6a0",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "waist-curves-enhance",
    name: "Enhance Waist Curves",
    nameAr: "إبراز منحنيات الخصر",
    category: "waist-belly",
    description: "Accentuate natural waist curves",
    descriptionAr: "إبراز المنحنيات الطبيعية للخصر",
    icon: "🌙",
    editMode: "curve",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 70,
    defaultBrushSize: 90,
    maxBrushSize: 180,
    defaultFeather: 25,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff6b9d",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "belly-enhance",
    name: "Enhance Belly",
    nameAr: "زيادة بروز البطن",
    category: "waist-belly",
    description: "Add volume to belly area",
    descriptionAr: "إضافة حجم لمنطقة البطن",
    icon: "🤰",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 75,
    defaultBrushSize: 110,
    maxBrushSize: 210,
    defaultFeather: 35,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ffd23f",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "torso-tighten",
    name: "Tighten Torso",
    nameAr: "شدّ الجذع والوسط",
    category: "waist-belly",
    description: "Tighten and tone entire torso area",
    descriptionAr: "شد وتنسيق منطقة الجذع والوسط بالكامل",
    icon: "💎",
    editMode: "sculpt",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 85,
    defaultBrushSize: 140,
    maxBrushSize: 280,
    defaultFeather: 50,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#4ecdc4",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "hips-lower",
    name: "Lower Hips",
    nameAr: "إنزا�� الحوض",
    category: "waist-belly",
    description: "Lower hip position for different proportions",
    descriptionAr: "خفض موضع الحوض للحصول على نسب مختلفة",
    icon: "⬇️",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 160,
    maxBrushSize: 320,
    defaultFeather: 60,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#845ec2",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
];

// Chest Tools (6 tools)
export const CHEST_TOOLS: VisualPatchTool[] = [
  {
    id: "chest-lift",
    name: "Lift Chest",
    nameAr: "رفع الصدر",
    category: "chest",
    description: "Lift and enhance chest position",
    descriptionAr: "رفع وتحسين موضع الصدر",
    icon: "⬆️",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 70,
    defaultBrushSize: 80,
    maxBrushSize: 160,
    defaultFeather: 20,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff9999",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "chest-reduce",
    name: "Reduce Chest",
    nameAr: "تصغير الصدر",
    category: "chest",
    description: "Reduce chest size naturally",
    descriptionAr: "تقليل حجم الصدر بشكل طبيعي",
    icon: "🔻",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 80,
    defaultBrushSize: 70,
    maxBrushSize: 140,
    defaultFeather: 18,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#99ccff",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "chest-enhance",
    name: "Enhance Chest",
    nameAr: "تكبير الصدر",
    category: "chest",
    description: "Enhance chest size and volume",
    descriptionAr: "زيادة حجم ومقدار الصدر",
    icon: "🔺",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 75,
    defaultBrushSize: 75,
    maxBrushSize: 150,
    defaultFeather: 20,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ffcc99",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "chest-reshape",
    name: "Reshape Chest",
    nameAr: "إعادة تشكيل الصدر",
    category: "chest",
    description: "Reshape chest contours and form",
    descriptionAr: "إعادة تشكيل محيط وشكل الصدر",
    icon: "🔄",
    editMode: "sculpt",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 65,
    maxBrushSize: 130,
    defaultFeather: 15,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#cc99ff",
    overlayOpacity: 0.35,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "chest-balance",
    name: "Balance Chest",
    nameAr: "موازنة الطرفين",
    category: "chest",
    description: "Balance left and right chest sides",
    descriptionAr: "موازنة الجانب الأيسر والأيمن للصدر",
    icon: "⚖️",
    editMode: "mirror",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 85,
    maxBrushSize: 170,
    defaultFeather: 22,
    supportsSymmetry: false,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#99ffcc",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "chest-flatten",
    name: "Flatten Chest",
    nameAr: "تسطيح الصدر",
    category: "chest",
    description: "Flatten chest area for general use",
    descriptionAr: "تسطيح منطقة الصدر للاستخدام العام",
    icon: "📏",
    editMode: "sculpt",
    enabled: true,
    defaultIntensity: 35,
    maxIntensity: 90,
    defaultBrushSize: 90,
    maxBrushSize: 180,
    defaultFeather: 25,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ffff99",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
];

// Hips & Thighs Tools (6 tools)
export const HIPS_THIGHS_TOOLS: VisualPatchTool[] = [
  {
    id: "hips-enhance",
    name: "Enhance Hips",
    nameAr: "تكبير الأرداف",
    category: "hips-thighs",
    description: "Enhance hip size and curves",
    descriptionAr: "زيادة حجم ومنحنيات الأرداف",
    icon: "🍑",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 85,
    defaultBrushSize: 120,
    maxBrushSize: 240,
    defaultFeather: 35,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff6b8a",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "butt-lift",
    name: "Lift Butt",
    nameAr: "رفع المؤخرة",
    category: "hips-thighs",
    description: "Lift and firm buttocks area",
    descriptionAr: "رفع وشد منطقة المؤخرة",
    icon: "⬆️",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 75,
    defaultBrushSize: 100,
    maxBrushSize: 200,
    defaultFeather: 30,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#4dabf7",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "hips-slim",
    name: "Slim Hips",
    nameAr: "تنحيف الأرداف",
    category: "hips-thighs",
    description: "Reduce hip width for slimmer silhouette",
    descriptionAr: "تقليل عرض الأرداف للحصول على شكل أنحف",
    icon: "⬅️➡️",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 70,
    defaultBrushSize: 110,
    maxBrushSize: 220,
    defaultFeather: 32,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ew-resize",
    previewColor: "#69db7c",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "thighs-smooth",
    name: "Smooth Thighs",
    nameAr: "تنعيم الفخذين",
    category: "hips-thighs",
    description: "Smooth and contour thigh areas",
    descriptionAr: "تنعيم وتحديد منطقة الفخذين",
    icon: "✨",
    editMode: "smooth",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 95,
    maxBrushSize: 190,
    defaultFeather: 28,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ffa94d",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "thighs-slim",
    name: "Slim Thighs",
    nameAr: "تنحيف الفخذين",
    category: "hips-thighs",
    description: "Reduce thigh circumference",
    descriptionAr: "تقليل محيط الفخذين",
    icon: "🦵",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 80,
    defaultBrushSize: 90,
    maxBrushSize: 180,
    defaultFeather: 25,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#da77f2",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "hips-shape",
    name: "Shape Hips",
    nameAr: "تحسين شكل الأرداف",
    category: "hips-thighs",
    description: "Improve overall hip shape and proportions",
    descriptionAr: "تحسين الشكل العام ونسب الأرداف",
    icon: "🎨",
    editMode: "sculpt",
    enabled: true,
    defaultIntensity: 22,
    maxIntensity: 65,
    defaultBrushSize: 115,
    maxBrushSize: 230,
    defaultFeather: 38,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#74c0fc",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
];

// Legs & Feet Tools (6 tools)
export const LEGS_FEET_TOOLS: VisualPatchTool[] = [
  {
    id: "legs-lengthen",
    name: "Lengthen Legs",
    nameAr: "تطويل الساقين",
    category: "legs-feet",
    description: "Extend leg length for taller appearance",
    descriptionAr: "إطالة الساقين للحصول على مظهر أطول",
    icon: "📏",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 65,
    defaultBrushSize: 140,
    maxBrushSize: 280,
    defaultFeather: 45,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#51cf66",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "legs-shorten",
    name: "Shorten Legs",
    nameAr: "تقصير الساقين",
    category: "legs-feet",
    description: "Reduce leg length proportionally",
    descriptionAr: "تقليل طول الساقين بشكل متناسب",
    icon: "📐",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 140,
    maxBrushSize: 280,
    defaultFeather: 45,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#ff8cc8",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "legs-slim",
    name: "Slim Legs",
    nameAr: "تنحيف الساقين",
    category: "legs-feet",
    description: "Make legs appear slimmer and more toned",
    descriptionAr: "جعل الساقين تبدو أنحف ومشدودة أكثر",
    icon: "🦵",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 75,
    defaultBrushSize: 85,
    maxBrushSize: 170,
    defaultFeather: 25,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#339af0",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "legs-bulk",
    name: "Bulk Legs",
    nameAr: "تضخيم الساقين",
    category: "legs-feet",
    description: "Add muscle definition and size to legs",
    descriptionAr: "إضافة تعريف عضلي وحجم للساقين",
    icon: "💪",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 22,
    maxIntensity: 70,
    defaultBrushSize: 90,
    maxBrushSize: 180,
    defaultFeather: 28,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#fd7e14",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "knees-adjust",
    name: "Adjust Knee Curves",
    nameAr: "ضبط انحناء الركبتين",
    category: "legs-feet",
    description: "Adjust knee alignment and curvature",
    descriptionAr: "ضبط استقامة وانحناء الركبتين",
    icon: "🔄",
    editMode: "curve",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 45,
    defaultBrushSize: 60,
    maxBrushSize: 120,
    defaultFeather: 18,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#845ef7",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "ankles-slim",
    name: "Slim Ankles",
    nameAr: "تصغير الكاحلين",
    category: "legs-feet",
    description: "Refine ankle area for more elegant legs",
    descriptionAr: "تنقيح منطقة الكاحل للحصول على ساقين أكثر أناقة",
    icon: "👠",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 45,
    maxBrushSize: 90,
    defaultFeather: 12,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#f783ac",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "low",
  },
];

// Arms & Shoulders Tools (6 tools)
export const ARMS_SHOULDERS_TOOLS: VisualPatchTool[] = [
  {
    id: "arms-slim",
    name: "Slim Arms",
    nameAr: "تنحيف الذراعين",
    category: "arms-shoulders",
    description: "Make arms appear slimmer and more toned",
    descriptionAr: "جعل الذراعين تبدو أنحف ومشدودة أكثر",
    icon: "💪",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 75,
    defaultBrushSize: 70,
    maxBrushSize: 140,
    defaultFeather: 20,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#20c997",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "arms-bulk",
    name: "Bulk Arms",
    nameAr: "تضخيم الذراعين",
    category: "arms-shoulders",
    description: "Add muscle definition and size to arms",
    descriptionAr: "إضافة تعريف عضلي وحجم للذراعين",
    icon: "🦾",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 22,
    maxIntensity: 70,
    defaultBrushSize: 75,
    maxBrushSize: 150,
    defaultFeather: 22,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff6b35",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "shoulders-adjust",
    name: "Adjust Shoulders",
    nameAr: "توسيع أو تصغير الكتفين",
    category: "arms-shoulders",
    description: "Widen or narrow shoulder width",
    descriptionAr: "توسيع أو تضييق عرض الكتفين",
    icon: "🏋️",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 65,
    defaultBrushSize: 110,
    maxBrushSize: 220,
    defaultFeather: 35,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ew-resize",
    previewColor: "#4c6ef5",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "elbows-smooth",
    name: "Smooth Elbows",
    nameAr: "تنعيم المرفقين",
    category: "arms-shoulders",
    description: "Smooth elbow area for better arm lines",
    descriptionAr: "تنعيم منطقة المرفق للحصول على خطوط ذراع أفضل",
    icon: "✨",
    editMode: "smooth",
    enabled: true,
    defaultIntensity: 18,
    maxIntensity: 55,
    defaultBrushSize: 55,
    maxBrushSize: 110,
    defaultFeather: 15,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#7c3aed",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "hands-slim",
    name: "Slim Hands",
    nameAr: "تصغير اليدين",
    category: "arms-shoulders",
    description: "Refine hand size and shape",
    descriptionAr: "تنقيح حجم وشكل اليدين",
    icon: "🤏",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 40,
    maxBrushSize: 80,
    defaultFeather: 10,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#f59e0b",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "arms-lengthen",
    name: "Lengthen Arms",
    nameAr: "تطويل الذراعين",
    category: "arms-shoulders",
    description: "Extend arm length proportionally",
    descriptionAr: "إطالة الذراعين بشكل متناسب",
    icon: "📏",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 50,
    defaultBrushSize: 100,
    maxBrushSize: 200,
    defaultFeather: 30,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ns-resize",
    previewColor: "#06ffa5",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "high",
  },
];

// Head & Face Tools (6 tools)
export const HEAD_FACE_TOOLS: VisualPatchTool[] = [
  {
    id: "face-resize",
    name: "Resize Face",
    nameAr: "تكبير/تصغير الوجه",
    category: "head-face",
    description: "Scale face size up or down",
    descriptionAr: "تكبير أو تصغير حجم الوجه",
    icon: "😀",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 80,
    maxBrushSize: 160,
    defaultFeather: 25,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ffd43b",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "cheeks-lift",
    name: "Lift Cheeks",
    nameAr: "رفع الخدين",
    category: "head-face",
    description: "Lift and enhance cheek area",
    descriptionAr: "رفع وتحسين منطقة الخدين",
    icon: "😊",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 18,
    maxIntensity: 55,
    defaultBrushSize: 50,
    maxBrushSize: 100,
    defaultFeather: 15,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff8fab",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "jaw-slim",
    name: "Slim Jaw",
    nameAr: "تنحيف الفك",
    category: "head-face",
    description: "Narrow jawline for refined look",
    descriptionAr: "تضييق خط الفك للحصو�� على مظهر مُنقح",
    icon: "💎",
    editMode: "pinch",
    enabled: true,
    defaultIntensity: 22,
    maxIntensity: 65,
    defaultBrushSize: 60,
    maxBrushSize: 120,
    defaultFeather: 18,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#74c0fc",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "forehead-widen",
    name: "Widen Forehead",
    nameAr: "توسيع الجبهة",
    category: "head-face",
    description: "Expand forehead area",
    descriptionAr: "توسيع منطقة الجبهة",
    icon: "🧠",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 15,
    maxIntensity: 45,
    defaultBrushSize: 70,
    maxBrushSize: 140,
    defaultFeather: 20,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "ew-resize",
    previewColor: "#91a7ff",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "ears-adjust",
    name: "Adjust Ears",
    nameAr: "تعديل الأذنين",
    category: "head-face",
    description: "Resize and reposition ears",
    descriptionAr: "تغيير حجم وموضع الأذنين",
    icon: "👂",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 60,
    defaultBrushSize: 35,
    maxBrushSize: 70,
    defaultFeather: 10,
    supportsSymmetry: true,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#ff9f43",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "face-symmetry",
    name: "Face Symmetry",
    nameAr: "ضبط التماثل الوجهي",
    category: "head-face",
    description: "Balance facial symmetry",
    descriptionAr: "موازنة التماثل في الوجه",
    icon: "⚖️",
    editMode: "mirror",
    enabled: true,
    defaultIntensity: 12,
    maxIntensity: 40,
    defaultBrushSize: 90,
    maxBrushSize: 180,
    defaultFeather: 30,
    supportsSymmetry: false,
    requiresRegionSelection: true,
    cursorIcon: "crosshair",
    previewColor: "#0ca678",
    overlayOpacity: 0.25,
    realTimePreview: true,
    processingComplexity: "low",
  },
];

// Freeform Tools (6 tools)
export const FREEFORM_TOOLS: VisualPatchTool[] = [
  {
    id: "freeform-brush",
    name: "Manual Brush",
    nameAr: "أداة الفرشاة اليدوية",
    category: "freeform",
    description: "Free-hand brush editing with custom strokes",
    descriptionAr: "تحرير بالفرشاة اليدوية مع ضربات مخصصة",
    icon: "🖌️",
    editMode: "brush",
    enabled: true,
    defaultIntensity: 25,
    maxIntensity: 100,
    defaultBrushSize: 50,
    maxBrushSize: 200,
    defaultFeather: 20,
    supportsSymmetry: false,
    requiresRegionSelection: false,
    cursorIcon: "crosshair",
    previewColor: "#fff",
    overlayOpacity: 0.4,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "freeform-warp",
    name: "Free Warp",
    nameAr: "أداة التشويه الحر",
    category: "freeform",
    description: "Advanced warping with custom control points",
    descriptionAr: "تشويه متقدم مع نقاط تحكم مخصصة",
    icon: "🌀",
    editMode: "warp",
    enabled: true,
    defaultIntensity: 30,
    maxIntensity: 90,
    defaultBrushSize: 80,
    maxBrushSize: 300,
    defaultFeather: 35,
    supportsSymmetry: false,
    requiresRegionSelection: false,
    cursorIcon: "move",
    previewColor: "#64ffda",
    overlayOpacity: 0.35,
    realTimePreview: true,
    processingComplexity: "high",
  },
  {
    id: "freeform-curve",
    name: "Curve Tool",
    nameAr: "أداة المنحنى",
    category: "freeform",
    description: "Create smooth curves and flowing lines",
    descriptionAr: "إنشاء منحنيات ناعمة وخطوط متدفقة",
    icon: "〰️",
    editMode: "curve",
    enabled: true,
    defaultIntensity: 20,
    maxIntensity: 70,
    defaultBrushSize: 60,
    maxBrushSize: 150,
    defaultFeather: 25,
    supportsSymmetry: false,
    requiresRegionSelection: false,
    cursorIcon: "crosshair",
    previewColor: "#ff6348",
    overlayOpacity: 0.3,
    realTimePreview: true,
    processingComplexity: "medium",
  },
  {
    id: "freeform-mirror",
    name: "Mirror/Flip",
    nameAr: "أداة عكس الجهة",
    category: "freeform",
    description: "Mirror or flip selected areas",
    descriptionAr: "عكس أو قلب المناطق المحددة",
    icon: "🪞",
    editMode: "mirror",
    enabled: true,
    defaultIntensity: 100,
    maxIntensity: 100,
    defaultBrushSize: 100,
    maxBrushSize: 400,
    defaultFeather: 0,
    supportsSymmetry: false,
    requiresRegionSelection: true,
    cursorIcon: "copy",
    previewColor: "#9c88ff",
    overlayOpacity: 0.5,
    realTimePreview: false,
    processingComplexity: "low",
  },
  {
    id: "freeform-highlighter",
    name: "Before/After Highlighter",
    nameAr: "أداة التظليل قبل/بعد",
    category: "freeform",
    description: "Highlight areas to show before/after changes",
    descriptionAr: "تسليط الضوء على المناطق لإظهار التغييرات قبل/بعد",
    icon: "🔦",
    editMode: "brush",
    enabled: true,
    defaultIntensity: 50,
    maxIntensity: 100,
    defaultBrushSize: 80,
    maxBrushSize: 200,
    defaultFeather: 40,
    supportsSymmetry: false,
    requiresRegionSelection: false,
    cursorIcon: "crosshair",
    previewColor: "#ffeb3b",
    overlayOpacity: 0.6,
    realTimePreview: true,
    processingComplexity: "low",
  },
  {
    id: "freeform-reset",
    name: "Reset Areas",
    nameAr: "أداة إعادة الشكل الأصلي",
    category: "freeform",
    description: "Reset selected areas to original state",
    descriptionAr: "إعادة المناطق المحددة إلى الحالة الأصلية",
    icon: "🔄",
    editMode: "brush",
    enabled: true,
    defaultIntensity: 100,
    maxIntensity: 100,
    defaultBrushSize: 70,
    maxBrushSize: 180,
    defaultFeather: 30,
    supportsSymmetry: false,
    requiresRegionSelection: false,
    cursorIcon: "not-allowed",
    previewColor: "#ff5722",
    overlayOpacity: 0.4,
    realTimePreview: true,
    processingComplexity: "low",
  },
];

// All tools combined
export const ALL_VISUAL_PATCH_TOOLS: VisualPatchTool[] = [
  ...BODY_SCALE_TOOLS,
  ...WAIST_BELLY_TOOLS,
  ...CHEST_TOOLS,
  ...HIPS_THIGHS_TOOLS,
  ...LEGS_FEET_TOOLS,
  ...ARMS_SHOULDERS_TOOLS,
  ...HEAD_FACE_TOOLS,
  ...FREEFORM_TOOLS,
];

export interface VisualPatchLabState {
  currentSession: EditSession | null;
  activeTool: string | null;
  toolSettings: ToolSettings;
  canvasState: CanvasState;
  history: EditHistory;
  isProcessing: boolean;
  showBeforeAfter: boolean;
  gridVisible: boolean;
  guidesVisible: boolean;
}

export interface VisualPatchLabActions {
  createSession: (imageFile: File) => Promise<string>;
  loadSession: (sessionId: string) => Promise<void>;
  saveSession: () => Promise<void>;
  selectTool: (toolId: string) => void;
  applyTool: (regions: EditRegion[]) => Promise<void>;
  undo: () => void;
  redo: () => void;
  resetToOriginal: () => void;
  exportImage: (options: ExportOptions) => Promise<string>;
  toggleBeforeAfter: () => void;
  updateToolSettings: (settings: Partial<ToolSettings>) => void;
  updateCanvasState: (state: Partial<CanvasState>) => void;
}
